
create table person
(
    id int8 not null generated by default as identity ,
    course integer,
    first_name varchar(255),
    institute varchar(255),
    last_name varchar(255),
    middle_name varchar(255),
    last_name_and_initials varchar(255),
    phone varchar(255) unique,
    phone_confirmed boolean,
    email varchar(255) unique,
    password varchar(255) unique,
    role varchar(255),
    post varchar(255),
    structure varchar(255),
    provider varchar(255),
    provider_id varchar(255),
    primary key (id)
);

create table token
(
  id int8 not null generated by default as identity ,
  token varchar(255) unique ,
  revoked boolean,
  expired boolean,
  token_type varchar(255),
  person_id int8 not null references person

);
create table roomhall
(
    id int8 not null generated by default as identity,
    address varchar(255),
    eng_name varchar(255),
    lat varchar(255),
    lon varchar(255),
    name varchar(255),
    primary key (id)
);

create table if not exists booking
(
   id int8 not null generated by default as identity,
   booked_at timestamp,
   comment varchar(2048),
   date date,
   time_end time,
   time_start time,
   confirmed boolean,
   person_id int8 not null references person,
   roomhall_id int8 not null references roomhall,
   primary key (id)
);

insert into roomhall(address,name,eng_name,lat,lon) values (
               'ул. Гоголя, 14, Севастополь',
               'Зеркальный зал', 'zerkalniy-zal-gogolya',
               '44.597699', '33.519961'
           );
insert into roomhall(address,name,eng_name,lat,lon) values (
               'ул. Гоголя, 14, Севастополь',
               'Холл 2', 'hall2-gogolya',
               '44.597699', '33.519961'
           );
insert into roomhall(address,name,eng_name,lat,lon) values (
               'ул. Гоголя, 14, Севастополь',
               'Холл 3', 'hall3-gogolya',
               '44.597699', '33.519961'
           );
insert into roomhall(address,name,eng_name,lat,lon) values (
               'ул. Гоголя, 14, Севастополь',
               'Актовый зал', 'actoviy-zal-gogolya',
               '44.597699', '33.519961'
           );
insert into roomhall(address,name,eng_name,lat,lon) values (
               'ул. Курчатова, 7, Севастополь',
               'Актовый зал', 'actoviy-zal-kurchatova',
               '44.624367', '33.519961'
           );